# -*- coding: utf-8 -*-
"""2Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahOdVpSvxBSNub1nwoQqnu8wxyheUZsL
"""

"""
2 - Solicitar 5 números, ao fim, imprimir o
número maior e o número menor
"""

lista = []
for i in range (5):
  lista.append(int(input(f"Digite o {i + 1}° número: ")))

print("=-="*8)

print(f"O maior número digitado é {max(lista)}, e o menor é {min(lista)}")