# -*- coding: utf-8 -*-
"""4Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uZdjGv7Z5MBwB2e2iNLkcpRjE1QClk8g
"""

"""
4 - Criar um vetor de cinco posições,
solicitar cinco números e ao fim, imprimir
o valor apresentado na posição três
"""

lista = []
for i in range (5):
  lista.append(int(input(f"Digite o {i + 1}° número: ")))

print("=-="*8)

print(f"Em Python, vetores/listas começam com a posição/índice 0 (zero),\n"
      f"então o 3° número seria {lista[2]}, localizado na 2° posição/índice,\n"
      f"mas a 3° posição/índice seria {lista[3]}, sendo o 4° número digitado")