# -*- coding: utf-8 -*-
"""5Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VV88LeEXdJTQh8Ln-aSlWwX7H55J6b5S
"""

"""
5 - Crie uma matriz bidimensional. Deverá
ser solicitado três nomes de alunos e
quatro notas, após solicitação dos nomes
e das notas deverá ser impresso os nomes
acompanhados da média geral de cada
aluno, deverá ser impresso também o
nome do aluno que obteve a maior média
e o nome do aluno que obteve a menor
média
"""

nomes = []
notas = [[], [], []]
medias = []

for i in range(3):
  print("-")
  nome = input("Nome do Aluno: ")
  nomes.append(nome)
  print("-")
  for j in range(4):
    nota = -1
    while nota < 0 or nota > 10:
      nota = float(input(f"{j + 1}° nota do Aluno {nome}: "))
      if nota < 0 or nota > 10:
          print("Valor Inválido! Notas entre 0 e 10")
          continue
      else:
        notas[i].append(nota)

print("=-="*8)

for i in range(len(notas)):
  medias.append(sum(notas[i]) / len(notas[i]))

for i in range(len(nomes)):
  print(f"O Aluno {nomes[i]} obteve a média de {medias[i]}")
  print("-")

maior = medias.index(max(medias))
menor = medias.index(min(medias))

print(f"O Aluno com maior média foi {nomes[maior]} com {max(medias)},"
      f"e o aluno com menor média foi {nomes[menor]} com {min(medias)}")